### ISSUE TITLE
Segmentation online

### ISSUE THREAD

**Issue by aarjayparashar** [NVlabs/BundleSDF#83] opened 2023-08-29 02:55 UTC
I wish to run this on real time image stream from Intel RealSense d435i. Can anyone guide me on getting the online segmentation done? Will be of great help. Thank you!

**Comment by wenbowen123** [comment] 2023-09-07 17:59
Duplicate of https://github.com/NVlabs/BundleSDF/issues/77

**Closed by wenbowen123** 2023-09-07 17:59 UTC
